kind: Pod
apiVersion: v1
metadata:
  name: nginx-azure-file-dynamic-1
spec:
  containers:
  - name: nginx-azure-file-dynamic-1
    image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    volumeMounts:
    - mountPath: "/home/smartide"
      name: ws-volume
      subPath: "home/smartide"
    - mountPath: "/home/project/"
      name: ws-volume
      subPath: "home/project/"
    - mountPath: "/smartide-data"
      name: ws-volume
      subPath: "smartide-data"
  nodeName: aks-nodepool1-12796734-vmss000000
  volumes:
    - name: ws-volume
      persistentVolumeClaim:
        claimName: smartide-wsxxx-pvc