kind: Pod
apiVersion: v1
metadata:
  name: nginx-managed-disk-dynamic-2
spec:
  containers:
    - name: nginx-managed-disk-dynamic-2
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: managed-disk-dynamic-pvc